spring:
  application:
    name: companies-crud
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
  datasource:
    url: "${db.url}"
    username: "${db.username}"
    password: "${db.password}"
    hikari:
      connection-timeout: "${db.connection-timeout}"
      maximum-pool-size: "${db.maximum-pool-size}" 
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    context-path: /companies-crud
  port: 8081
eureka:
    instance:
        instance-id: "${spring.application.name}:${random.value}"
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
