server:
    port: 7777

spring:
    profiles:
        active: default
    application:
        name: config-server

    cloud:
        config:
            server:
                git:
                    username: avaraslillo
                    password: ${GIT_TOKEN} 
                    uri: https://github.com/avaraslillo/microServicesConfig.git
                    default-label: main
                    clone-on-start: true
eureka:
    instance:
        instance-id: "${spring.application.name}:${random.value}"
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
